[package]
name = "ansi-to-png"
version = "0.1.0"
authors = ["Odin Dutton <odindutton@gmail.com>"]
edition = "2018"

[dependencies]
vte = "0.8.0"
image = "0.23.4"
clap = "3.0.0-beta.1"
freetype-rs = "0.25.0"
